# Generated by Django 5.2.16 on 2026-07-21 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='identifiant')),
                ('summary', models.CharField(max_length=200, verbose_name='accroche')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('ARTISANAT', 'Artisanat'), ('COMMERCE', 'Commerce'), ('AGRICULTURE', 'Agriculture'), ('EDUCATION', 'Éducation'), ('SANTE', 'Santé'), ('TECHNOLOGIE', 'Technologie'), ('CULTURE', 'Culture'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='catégorie')),
                ('goal_amount', models.PositiveIntegerField(verbose_name='objectif (FCFA)')),
                ('collected_amount', models.PositiveIntegerField(default=0, verbose_name='montant collecté (FCFA)')),
                ('cover_image', models.ImageField(blank=True, upload_to='campaigns/%Y/%m/', verbose_name='image de couverture')),
                ('deadline', models.DateField(verbose_name='échéance')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_MODERATION', 'En modération'), ('PUBLIEE', 'Publiée'), ('REJETEE', 'Rejetée'), ('CLOTUREE', 'Clôturée')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('moderation_note', models.TextField(blank=True, verbose_name='motif de modération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publiée le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='porteur')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='publiée le')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns.campaign', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'actualité de campagne',
                'verbose_name_plural': 'actualités de campagne',
                'ordering': ['-created_at'],
            },
        ),
    ]
