# Generated by Django 5.2.16 on 2026-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='beneficiaries',
            field=models.CharField(blank=True, max_length=180, verbose_name='bénéficiaires attendus'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='funding_plan',
            field=models.TextField(blank=True, verbose_name='utilisation prévue des fonds'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='localisation'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_timeline',
            field=models.TextField(blank=True, verbose_name='calendrier prévisionnel'),
        ),
    ]
