# Generated by Django 5.2.16 on 2026-07-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_workflow_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('DON_LIBRE', 'Don libre'), ('DON_CONTREPARTIE', 'Don avec contrepartie')], default='DON_LIBRE', max_length=20, verbose_name='type de campagne'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('minimum_amount', models.PositiveIntegerField(verbose_name='montant minimum (FCFA)')),
                ('quantity_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantité disponible')),
                ('quantity_claimed', models.PositiveIntegerField(default=0, verbose_name='quantité réservée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='campaigns.campaign', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'contrepartie',
                'verbose_name_plural': 'contreparties',
                'ordering': ['minimum_amount'],
            },
        ),
    ]
