# Generated by Django 5.2.16 on 2026-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_campaign_type_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='expected_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='taux de rendement attendu (%)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('DON_LIBRE', 'Don libre'), ('DON_CONTREPARTIE', 'Don avec contrepartie'), ('INVESTISSEMENT_PARTICIPATIF', 'Investissement participatif')], default='DON_LIBRE', max_length=30, verbose_name='type de campagne'),
        ),
    ]
