# Generated by Django 5.2.16 on 2026-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_dossier_fee_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='presentation_video',
            field=models.FileField(blank=True, upload_to='campaigns/videos/%Y/%m/', verbose_name='vidéo de présentation'),
        ),
    ]
