# Generated by Django 5.2.16 on 2026-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_presentation_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='presentation_video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de la vidéo de présentation'),
        ),
    ]
