# Generated by Django 5.2.16 on 2026-07-22 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACCOUNT_CREATED', 'Compte créé'), ('KYC_VALIDATED', 'KYC validé'), ('KYC_REJECTED', 'KYC rejeté'), ('CAMPAIGN_PUBLISHED', 'Campagne publiée'), ('CAMPAIGN_REJECTED', 'Campagne rejetée'), ('CONTRIBUTION_CONFIRMED', 'Contribution confirmée'), ('CONTRIBUTION_RECEIVED', 'Contribution reçue'), ('GOAL_REACHED', 'Objectif atteint')], max_length=30, verbose_name='type')),
                ('subject', models.CharField(max_length=160, verbose_name='objet')),
                ('message', models.TextField(verbose_name='message')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name="lien d'action")),
                ('delivery_status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échec')], default='PENDING', max_length=10, verbose_name='statut e-mail')),
                ('delivery_error', models.CharField(blank=True, max_length=255, verbose_name="erreur d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
