# Generated by Django 5.2.16 on 2026-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Compte créé'), ('KYC_VALIDATED', 'KYC validé'), ('KYC_REJECTED', 'KYC rejeté'), ('CAMPAIGN_PUBLISHED', 'Campagne publiée'), ('CAMPAIGN_REJECTED', 'Campagne rejetée'), ('CAMPAIGN_SUSPENDED', 'Campagne suspendue'), ('CAMPAIGN_REACTIVATED', 'Campagne réactivée'), ('CAMPAIGN_CLOSED', 'Campagne clôturée'), ('CONTRIBUTION_CONFIRMED', 'Contribution confirmée'), ('CONTRIBUTION_RECEIVED', 'Contribution reçue'), ('GOAL_REACHED', 'Objectif atteint'), ('PAYOUT_RELEASED', 'Fonds reversés'), ('MESSAGE_RECEIVED', 'Nouveau message reçu'), ('DISPUTE_RESOLVED', 'Litige résolu'), ('ADMIN_ACTION_REQUIRED', 'Action administrateur requise')], max_length=30, verbose_name='type'),
        ),
    ]
