# Generated by Django 5.2.16 on 2026-07-28 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identifiant de vérification')),
                ('snapshot', models.JSONField(verbose_name="données figées à l'export")),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='généré le')),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_exports', to=settings.AUTH_USER_MODEL, verbose_name='porteur')),
            ],
            options={
                'verbose_name': 'export du Passeport Financier',
                'verbose_name_plural': 'exports du Passeport Financier',
                'ordering': ['-generated_at'],
            },
        ),
    ]
