# Generated by Django 5.2.16 on 2026-07-28 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0005_campaign_campaign_type_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier message le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to='campaigns.campaign', verbose_name='campagne')),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to=settings.AUTH_USER_MODEL, verbose_name='autre participant')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=3000, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messagethread', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(fields=('campaign', 'other_user'), name='unique_campaign_other_user_thread'),
        ),
    ]
