# Generated by Django 5.2.16 on 2026-07-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam ou sollicitation'), ('HARCELEMENT', 'Harcèlement'), ('CONTENU_INAPPROPRIE', 'Contenu inapproprié'), ('TENTATIVE_CONTOURNEMENT', 'Tentative de contournement de la plateforme'), ('AUTRE', 'Autre motif')], max_length=30, verbose_name='motif')),
                ('details', models.TextField(max_length=1500, verbose_name='précisions')),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours d’examen'), ('RESOLU', 'Résolu'), ('CLASSE', 'Classé sans suite')], default='NOUVEAU', max_length=20, verbose_name='statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_message_reports', to=settings.AUTH_USER_MODEL, verbose_name='attribué à')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message', verbose_name='message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur du signalement')),
            ],
            options={
                'verbose_name': 'signalement de message',
                'verbose_name_plural': 'signalements de messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
