# Generated by Django 5.2.16 on 2026-07-30 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nom du dispositif')),
                ('provider_name', models.CharField(max_length=160, verbose_name='organisme')),
                ('provider_type', models.CharField(choices=[('FONDS_PUBLIC', 'Fonds public'), ('BAILLEUR', 'Bailleur'), ('BANQUE', 'Banque partenaire'), ('PROGRAMME_APPUI', "Programme d'appui")], max_length=20, verbose_name="type d'organisme")),
                ('description', models.TextField(verbose_name='description')),
                ('website_url', models.URLField(blank=True, verbose_name='site web')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contact')),
                ('min_score', models.PositiveSmallIntegerField(default=0, verbose_name='score Jappandale minimum')),
                ('requires_kyc_valide', models.BooleanField(default=True, verbose_name='identité vérifiée requise')),
                ('diaspora_requirement', models.CharField(choices=[('INDIFFERENT', 'Indifférent'), ('DIASPORA_UNIQUEMENT', 'Réservé à la diaspora'), ('DIASPORA_EXCLUE', 'Diaspora non éligible')], default='INDIFFERENT', max_length=20, verbose_name='condition diaspora')),
                ('eligible_categories', models.JSONField(blank=True, default=list, verbose_name='catégories de projets éligibles')),
                ('eligible_regions', models.JSONField(blank=True, default=list, verbose_name='villes/régions éligibles')),
                ('min_goal_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='objectif de collecte minimum (FCFA)')),
                ('max_goal_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='objectif de collecte maximum (FCFA)')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='statut')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_schemes_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'dispositif de financement',
                'verbose_name_plural': 'dispositifs de financement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERET', 'Intérêt manifesté'), ('EN_COURS', 'Contact engagé'), ('ACCEPTE', 'Financement obtenu'), ('REFUSE', 'Refusé'), ('ABANDONNE', 'Abandonné')], default='INTERET', max_length=20, verbose_name='statut')),
                ('note', models.TextField(blank=True, verbose_name='note de suivi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='orienté le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_referrals', to=settings.AUTH_USER_MODEL, verbose_name='porteur')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='guichet.financingscheme', verbose_name='dispositif')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_referrals_updated', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'orientation vers un dispositif',
                'verbose_name_plural': 'orientations vers un dispositif',
                'ordering': ['-created_at'],
            },
        ),
    ]
