# Generated by Django 5.2.16 on 2026-07-28 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0006_payoutauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PROJET_NON_CONFORME', 'Projet non conforme / fonds mal utilisés'), ('PORTEUR_INJOIGNABLE', 'Porteur injoignable'), ('ERREUR_CONTRIBUTION', 'Contribution non voulue / erreur'), ('AUTRE', 'Autre motif')], max_length=30, verbose_name='motif')),
                ('details', models.TextField(max_length=1500, verbose_name='précisions')),
                ('status', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXAMEN', 'En examen'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20, verbose_name='statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='note interne')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='tranché le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL, verbose_name='attribué à')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='contributions.contribution', verbose_name='contribution')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL, verbose_name='auteur du litige')),
            ],
            options={
                'verbose_name': 'litige',
                'verbose_name_plural': 'litiges',
                'ordering': ['-created_at'],
            },
        ),
    ]
