# Generated by Django 5.2.16 on 2026-07-28 15:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_base', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5, verbose_name='score de base')),
                ('poids_kyc', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='bonus KYC validé')),
                ('poids_anciennete_max', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='bonus ancienneté (plafond)')),
                ('poids_activite_max', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='bonus activité (plafond)')),
                ('poids_reussite_max', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, verbose_name='bonus taux de réussite (plafond)')),
                ('poids_montant_max', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='bonus montant collecté (plafond)')),
                ('penalite_litige_max', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='pénalité litiges (plafond)')),
                ('penalite_signalement_unite', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='pénalité par signalement résolu')),
                ('penalite_signalement_max', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='pénalité signalements (plafond)')),
                ('penalite_campagne_rejetee_unite', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='pénalité par campagne rejetée/suspendue')),
                ('penalite_campagne_rejetee_max', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='pénalité campagnes rejetées (plafond)')),
            ],
            options={
                'verbose_name': 'réglages du Score Jappandale',
                'verbose_name_plural': 'réglages du Score Jappandale',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='score calculé')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='détail du calcul')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='surclassé manuellement')),
                ('override_value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='valeur imposée')),
                ('override_note', models.TextField(blank=True, verbose_name='justification de la validation humaine')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='calculé le')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL, verbose_name='surclassé par')),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='porteur')),
            ],
            options={
                'verbose_name': 'score Jappandale',
                'verbose_name_plural': 'scores Jappandale',
                'ordering': ['-computed_at'],
            },
        ),
    ]
