# Generated by Django 5.2.16 on 2026-07-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_review_note',
            field=models.TextField(blank=True, verbose_name='motif de la décision KYC'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de revue KYC'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='revu par'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('NON_SOUMIS', 'Non soumis'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='NON_SOUMIS', max_length=20, verbose_name='statut KYC'),
        ),
    ]
