# Generated by Django 5.2.16 on 2026-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminloginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_diaspora',
            field=models.BooleanField(default=False, verbose_name="réside à l'étranger (diaspora)"),
        ),
    ]
