# Generated by Django 5.2.16 on 2026-07-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_diaspora'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('SUSPENDU', 'Suspendu'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='statut du compte'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='statut de compte modifié le'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='statut modifié par'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status_note',
            field=models.TextField(blank=True, verbose_name='motif de la dernière décision'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROLE_CHANGED', 'Rôle modifié'), ('ACCOUNT_STATUS_CHANGED', 'Statut de compte modifié')], max_length=30, verbose_name='action')),
                ('previous_value', models.CharField(blank=True, max_length=50, verbose_name='valeur précédente')),
                ('new_value', models.CharField(blank=True, max_length=50, verbose_name='nouvelle valeur')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_user_audits', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'audit utilisateur",
                'verbose_name_plural': "journaux d'audit utilisateur",
                'ordering': ['-created_at'],
            },
        ),
    ]
