# Generated by Django 5.2.16 on 2026-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Compte créé par un administrateur'), ('ROLE_CHANGED', 'Rôle modifié'), ('ACCOUNT_STATUS_CHANGED', 'Statut de compte modifié'), ('INFO_UPDATED', 'Informations modifiées'), ('DELETED', 'Compte supprimé (anonymisé)')], max_length=30, verbose_name='action'),
        ),
    ]
