# Generated by Codex on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_user_audit_log_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("BANQUE", "Banque"),
                    ("INSTITUTION_PUBLIQUE", "Institution publique"),
                    ("INCUBATEUR", "Incubateur / accompagnateur"),
                    ("FONDS", "Fonds / investisseur"),
                    ("AUTRE", "Autre partenaire"),
                ],
                default="AUTRE",
                max_length=25,
                verbose_name="type de partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PORTEUR", "Porteur de projet"),
                    ("CONTRIBUTEUR", "Contributeur"),
                    ("PARTENAIRE", "Partenaire financier"),
                    ("ADMIN", "Administrateur"),
                ],
                default="CONTRIBUTEUR",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
    ]
