# Generated by Django 5.2.16 on 2026-07-22 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_beneficiaries_campaign_funding_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='référence publique')),
                ('amount', models.PositiveBigIntegerField(verbose_name='montant (FCFA)')),
                ('anonymous', models.BooleanField(default=False, verbose_name='contribution anonyme')),
                ('status', models.CharField(choices=[('INITIEE', 'Initiée'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée'), ('REMBOURSEE', 'Remboursée')], default='INITIEE', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmée le')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='remboursée le')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='campaigns.campaign', verbose_name='campagne')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='contributeur')),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SIMULATED', 'Paiement simulé')], default='SIMULATED', max_length=20, verbose_name='fournisseur')),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='référence fournisseur')),
                ('status', models.CharField(choices=[('INITIEE', 'Initiée'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée'), ('REMBOURSEE', 'Remboursée')], default='INITIEE', max_length=20, verbose_name='statut')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='contributions.contribution', verbose_name='contribution')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['campaign', 'status'], name='contributio_campaig_c7eb38_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contributor', 'status'], name='contributio_contrib_cc4945_idx'),
        ),
    ]
