# Generated by Django 5.2.16 on 2026-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('SIMULATED', 'Contribution Jappandale')], default='SIMULATED', max_length=20, verbose_name='fournisseur'),
        ),
    ]
