# Generated by Django 5.2.16 on 2026-07-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_campaign_type_reward'),
        ('contributions', '0002_alter_transaction_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='campaigns.reward', verbose_name='contrepartie'),
        ),
    ]
