# Generated by Django 5.2.16 on 2026-07-27 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4, verbose_name='taux de commission')),
            ],
            options={
                'verbose_name': 'réglages de la plateforme',
                'verbose_name_plural': 'réglages de la plateforme',
            },
        ),
    ]
