# Generated by Django 5.2.16 on 2026-07-27 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_campaign_type_reward'),
        ('contributions', '0004_platformsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='commission_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='montant de la commission (FCFA)'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='commission_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='taux de commission appliqué'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='net_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='montant net pour le porteur (FCFA)'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reversée le'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payout_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payouts', to=settings.AUTH_USER_MODEL, verbose_name='reversée par'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payout_status',
            field=models.CharField(choices=[('EN_SEQUESTRE', 'En séquestre'), ('REVERSEE', 'Reversée')], default='EN_SEQUESTRE', max_length=20, verbose_name='statut de reversement'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['campaign', 'payout_status'], name='contributio_campaig_78bb7f_idx'),
        ),
    ]
