# Generated by Django 5.2.16 on 2026-07-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_campaign_type_reward'),
        ('contributions', '0005_contribution_commission_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions_count', models.PositiveIntegerField(verbose_name='nombre de contributions reversées')),
                ('gross_amount', models.PositiveIntegerField(verbose_name='montant brut reversé (FCFA)')),
                ('commission_amount', models.PositiveIntegerField(verbose_name='commission totale (FCFA)')),
                ('net_amount', models.PositiveIntegerField(verbose_name='montant net reversé (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='effectué le')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_payout_releases', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_audit_logs', to='campaigns.campaign', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'événement de reversement',
                'verbose_name_plural': 'événements de reversement',
                'ordering': ['-created_at'],
            },
        ),
    ]
