# Generated by Django 5.2.16 on 2026-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_payoutauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='wants_to_be_shareholder',
            field=models.BooleanField(default=False, help_text="Uniquement significatif pour une campagne d'investissement participatif.", verbose_name='souhaite devenir actionnaire'),
        ),
    ]
