# Generated by Django 5.2.16 on 2026-09-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_contribution_wants_to_be_shareholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='shareholder_note',
            field=models.CharField(blank=True, max_length=1500, verbose_name='motif du refus (actionnariat)'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='shareholder_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='actionnariat examiné le'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='shareholder_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shareholder_requests', to=settings.AUTH_USER_MODEL, verbose_name='actionnariat examiné par'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='shareholder_status',
            field=models.CharField(choices=[('NON_DEMANDE', 'Non demandé'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='NON_DEMANDE', max_length=20, verbose_name='statut actionnaire'),
        ),
    ]
