# Generated by Django 5.2.16 on 2026-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_contribution_shareholder_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('SIMULATED', 'Contribution Jappandale'), ('PAYTECH', 'PayTech')], default='SIMULATED', max_length=20, verbose_name='fournisseur'),
        ),
    ]
