# Generated by Codex on 2026-09-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0006_investissement_participatif"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140, verbose_name="titre")),
                ("document_type", models.CharField(choices=[("BUSINESS_PLAN", "Business plan"), ("PITCH_DECK", "Pitch deck"), ("BUDGET", "Budget / prévisions"), ("JUSTIFICATIF", "Justificatif"), ("AUTRE", "Autre document")], default="AUTRE", max_length=25, verbose_name="type")),
                ("file", models.FileField(upload_to="project-documents/%Y/%m/", verbose_name="fichier")),
                ("shared_with_partners", models.BooleanField(default=True, verbose_name="partageable avec les partenaires financiers")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="téléversé le")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_documents", to="campaigns.campaign", verbose_name="projet")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_project_documents", to=settings.AUTH_USER_MODEL, verbose_name="téléversé par")),
            ],
            options={"verbose_name": "document de projet", "verbose_name_plural": "documents de projet", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PartnerProjectInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("INTERESSE", "Intéressé"), ("EN_COURS", "En cours d'étude"), ("CONTACTE", "Porteur contacté"), ("CLOTURE", "Clôturé")], default="INTERESSE", max_length=20)),
                ("note", models.TextField(blank=True, max_length=1000, verbose_name="note interne")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="mis à jour le")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="partner_interests", to="campaigns.campaign", verbose_name="projet")),
                ("partner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_interests", to=settings.AUTH_USER_MODEL, verbose_name="partenaire")),
            ],
            options={"verbose_name": "intérêt partenaire", "verbose_name_plural": "intérêts partenaires", "ordering": ["-updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="partnerprojectinterest",
            constraint=models.UniqueConstraint(fields=("partner", "campaign"), name="unique_partner_campaign_interest"),
        ),
    ]
