# Generated by Django 5.2.16 on 2026-07-21 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('JUSTIFICATIF_ACTIVITE', "Justificatif d'activité")], max_length=30, verbose_name='type de pièce')),
                ('file', models.FileField(upload_to='kyc/%Y/%m/', verbose_name='fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='téléversé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'document KYC',
                'verbose_name_plural': 'documents KYC',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
