# Generated by Django 5.2.16 on 2026-07-22 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DOCUMENT_SUBMITTED', 'Document déposé'), ('VALIDATED', 'Dossier validé'), ('REJECTED', 'Dossier rejeté')], max_length=30, verbose_name='action')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='ancien statut')),
                ('new_status', models.CharField(max_length=20, verbose_name='nouveau statut')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='effectuée le')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_kyc_actions', to=settings.AUTH_USER_MODEL, verbose_name="auteur de l'action")),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='kyc.kycdocument', verbose_name='document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "événement d'audit KYC",
                'verbose_name_plural': "événements d'audit KYC",
                'ordering': ['-created_at'],
            },
        ),
    ]
