# Generated by Django 5.2.16 on 2026-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('SELFIE', 'Selfie de vérification'), ('JUSTIFICATIF_ACTIVITE', "Justificatif d'activité")], max_length=30, verbose_name='type de pièce'),
        ),
    ]
