# Generated by Django 5.2.16 on 2026-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kycdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('SELFIE', 'Selfie de vérification'), ('JUSTIFICATIF_ACTIVITE', "Justificatif d'activité"), ('JUSTIFICATIF_RESIDENCE', "Justificatif de résidence à l'étranger"), ('JUSTIFICATIF_ORIGINE_FONDS', "Justificatif de l'origine des fonds")], max_length=30, verbose_name='type de pièce'),
        ),
    ]
