# Generated by Django 5.2.16 on 2026-10-04 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0009_campaign_presentation_video_url'),
        ('contributions', '0009_alter_transaction_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_command', models.CharField(max_length=60, unique=True, verbose_name='référence PayTech')),
                ('kind', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('DOSSIER_FEE', 'Frais de dossier')], max_length=20, verbose_name='nature')),
                ('amount', models.PositiveIntegerField(verbose_name='montant attendu (FCFA)')),
                ('status', models.CharField(choices=[('INITIEE', 'Initiée'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='INITIEE', max_length=20, verbose_name='statut')),
                ('paytech_token', models.CharField(blank=True, max_length=120, verbose_name='jeton PayTech')),
                ('payment_method', models.CharField(blank=True, max_length=60, verbose_name='moyen de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='campaigns.campaign', verbose_name='campagne (frais de dossier)')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contributions.contribution', verbose_name='contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='payeur')),
            ],
            options={
                'verbose_name': 'paiement PayTech',
                'verbose_name_plural': 'paiements PayTech',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contribution__isnull', False), ('kind', 'CONTRIBUTION')), models.Q(('campaign__isnull', False), ('kind', 'DOSSIER_FEE')), _connector='OR'), name='payment_target_matches_kind')],
            },
        ),
    ]
